before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc
  - sudo apt-get install -y texlive-full
  - sudo apt-get install -y texlive-xetex
  - chmod u+x ./travis/build.sh

script:
  - './travis/build.sh'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/publish.sh; fi'
